config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :admins

  resources :categories

  resources :promotions do
    member do 
      post 'creates_coupons'
      post 'approve'
    end
  end

  get 'search', to: 'promotions#search'

  resources :coupons, only: [] do
    member do
      post 'inactivate'
      post 'activate'
    end
  end

  namespace 'api', defaults: { format: :json } do
    namespace 'v1' do
      resources :coupons, only: [:show]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :code, presence: true, uniqueness: true
  has_many :category_promotions
end

app/models/category_promotion.rb
class CategoryPromotion < ApplicationRecord
  belongs_to :promotion
  belongs_to :category
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion

  validates :code, uniqueness: true

  enum status: { active: 0, inactive: 10 }
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :coupons, dependent: :destroy
  has_one :promotion_approval
  belongs_to :admin

  has_many :category_promotions
  has_many :categories, through: :category_promotions

  validates :name, :code, presence: true, uniqueness: true
  validates :discount_rate, :coupon_quantity, :expiration_date, presence: true

  def create_coupons!
    Coupon.transaction do
      1.upto(coupon_quantity) do |num|
        #transformar num array de hashes e fazer um insert all
        coupons.create!(code: "#{ code }-#{ num.to_s.rjust(4, '0') }")
      end
    end
  end

  def approve!(approval_admin)
    PromotionApproval.create(promotion: self, admin: approval_admin)
  end

  def approved?
    promotion_approval
  end

  def approver
    promotion_approval.admin
  end
end

app/models/promotion_approval.rb
class PromotionApproval < ApplicationRecord
  belongs_to :promotion
  belongs_to :admin

  validate :different_admin

  private

  def different_admin
    if promotion && promotion.admin == admin
      errors.add(:admin, 'nao pode ser o criador da promocao') 
    end
  end 
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API

end

app/controllers/api/v1/coupons_controller.rb
class Api::V1::CouponsController < ApplicationController
  def show
    @coupon = Coupon.find_by(code: params[:id])

    return render status: 404, json: "{ message: 'Coupon not found' }" if @coupon.nil?

    render json: @coupon.as_json(only: [:code, :status],
                                 include: {
                                    promotion: { only: :discount_rate }
                                 }), status: 200
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    return redirect_to @category if @category.save

    respond_to do |format|
      format.js { render partial: 'message' }
      format.html { render partial: 'result_message'}
    end
    #render :new
  end

  def show
  end

  def edit
  end

  def update
    return redirect_to @category if @category.update(category_params)

    respond_to do |format|
      format.js { render partial: 'message' }
      format.html { render partial: 'result_message'}
    end
    #render :edit
  end

  def destroy
    return redirect_to categories_path if @category.delete

    render :index
  end

  private

  def category_params
    params.require(:category).permit(:name, :code)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :authenticate_admin!

  def inactivate
    @coupon = Coupon.find(params[:id])
    @coupon.inactive!

    redirect_to @coupon.promotion
  end

  def activate
    @coupon = Coupon.find(params[:id])
    @coupon.active!

    redirect_to @coupon.promotion
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_promotion, except: %i[index new create search]

  def index
    @promotions = Promotion.all
  end

  def new
    @promotion = Promotion.new
    @categories = Category.all.order(name: :asc)
  end

  def create

    @promotion = Promotion.create(promotion_params)
    @promotion.admin = current_admin
    
    return redirect_to @promotion if @promotion.save

    respond_to do |format|
      format.js { render partial: 'message' }
      format.html { render partial: 'result_message'}
    end

    # @categories = Category.all.order(name: :asc)
    # render :new
  end

  def show
  end

  def edit
    @categories = Category.all.order(name: :asc)
  end

  def update
    return redirect_to @promotion if @promotion.update(promotion_params)

    respond_to do |format|
      format.js { render partial: 'message' }
      format.html { render partial: 'result_message'}
    end

    #@categories = Category.all.order(name: :asc)
    #render :edit
  end

  def destroy
    return redirect_to promotions_path if @promotion.destroy!

    render promotions_path
  end

  def creates_coupons
    return redirect_to @promotion, notice: t('.burned') if @promotion.coupons.any?
    @promotion.create_coupons!

    redirect_to @promotion, notice: t('.success')
  end

  def approve
    find_promotion.approve!(current_admin)
    redirect_to find_promotion
  end

  def search
    @result_set = Promotion.where('name like ? OR description like ?', 
                                  "%#{params[:q]}%",
                                  "%#{params[:q]}%")
    @result_set += (Coupon.where('code like ?', "%#{params[:q]}%"))
  end

  private

  def promotion_params
    params.require(:promotion).permit(:name, :description, :code, :discount_rate,
                                      :coupon_quantity, :expiration_date, category_ids: [] )
  end

  def find_promotion
    @promotion = Promotion.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<p><%= link_to  'Voltar', categories_path %></p>

<div id="mensagens"></div>

<%= form_with model: @category, local: false do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :code  %>
    <%= form.text_field :code %>
  </p>

  <%= form.submit %>
<% end %>

app/views/categories/_message.js.erb
document.querySelector('#mensagens').innerHTML = '<%= j render partial: 'result_message' %>'

app/views/categories/_result_message.html.erb
<% @category.errors.any? do %>
  <% @category.errors.full_messages.each do |message| %>
  <p><%= message %></p>
  <% end %>
<% end %>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<p><%= link_to  'Voltar', root_path %></p>

<h2><%= link_to 'Registrar uma categoria', new_category_path %></h2>

<hr>
<% @categories.each do |category|%>
  <h3>Nome: <%= link_to category.name, category %></h3>
  <p>Código: <%= category.code %></p>

  <p>
    <%= link_to 'Editar categoria', edit_category_path(category) %> | 
    <%= link_to 'Apagar categoria', category, method: :delete %>
  </p>
  <hr>
<% end %>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/categories/show.html.erb
<p><%= link_to  'Voltar', categories_path %></p>

<h3>Categoria: <%= @category.name %></h3>
<p>Código: <%= @category.code %></p>

<p>
  <%= link_to 'Editar categoria', edit_category_path(@category) %> | 
  <%= link_to 'Apagar categoria', @category, method: :delete %>
</p>

app/views/home/index.html.erb
<cite>Boas vindas ao sistema de gestão de promoções</cite>

<p><%= link_to 'Promoções', promotions_path %></p>
<p><%= link_to 'Categorias', categories_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PromotionSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/promotions/_form.html.erb
<p><%= link_to  'Voltar', promotions_path %></p>

<div id="mensagens">
</div>

<%= form_with model: @promotion, local: false do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :code  %>
    <%= form.text_field :code %>
  </p>

  <p>
    <%= form.label :discount_rate %>
    <%= form.number_field :discount_rate %>
  </p>

  <p>
    <%= form.label :coupon_quantity %>
    <%= form.number_field :coupon_quantity %>
  </p>

  <p>
    <%= form.label :expiration_date %>
    <%= form.date_field :expiration_date %>
  </p>

  <p>
    <%= form.collection_check_boxes :category_ids, @categories, :id, :name %>
  </p>

  <%= form.submit %>
<% end %>

app/views/promotions/_message.js.erb
document.querySelector('#mensagens').innerHTML = '<%= j render partial: 'result_message'  %>'

app/views/promotions/_result_message.html.erb
<% @promotion.errors.any? do %>
  <p><%= t :promotion_error_message %>
  <% @promotion.errors.full_messages.each do |message| %>
  <p><%= message %></p>
  <% end %>
<% end %>

app/views/promotions/index.html.erb
<p><%= link_to  'Voltar', root_path %></p>

<h2><%= link_to 'Registrar uma promoção', new_promotion_path %></h2>

<%= form_with url: search_path, method: :get do %>
  <%= label_tag :q, 'Buscar' %>
  <%= text_field_tag :q %>
  <%= submit_tag 'Pesquisar' %>
<% end %>

<% if @promotions.empty? %> 
  <p>Nenhuma promoção cadastrada</p>
<% end %>

<hr>
<% @promotions.each do |promotion|%>
  <h3>Promoção: <%= link_to promotion.name, promotion %></h3>
  <p>Descrição: <%= promotion.description %></p>
  <p>Código: <%= promotion.code %></p>
  <p>Desconto: <%= number_to_percentage promotion.discount_rate, precision: 2, separator: ',' %></p>
  <p>Quantidade de cupons: <%= promotion.coupon_quantity %></p>
  <p>Data de expiração: <%= I18n.localize(promotion.expiration_date) %></p>

  <p>
    <%= link_to 'Editar promoção', edit_promotion_path(promotion) %> | 
    <%= link_to 'Apagar promoção', promotion, method: :delete %>
  </p>

  <hr>
<% end %>

app/views/promotions/new.html.erb
<% @promotion.errors.any? do %>
  <% @promotion.errors.full_messages.each do |message| %>
  <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @promotion, local: true do |form| %>

  <p><%= form.label :name, 'Nome'  %>
  <%= form.text_field :name %></p>

  <p><%= form.label :description, 'Descrição' %>
  <%= form.text_field :description %></p>

  <p><%= form.label :code, 'Código' %>
  <%= form.text_field :code %></p>

  <p><%= form.label :discount_rate, 'Desconto' %>
  <%= form.number_field :discount_rate %></p>

  <p><%= form.label :coupon_quantity, 'Quantidade de cupons' %>
  <%= form.number_field :coupon_quantity %></p>

  <p><%= form.label :expiration_date, 'Data de término' %>
  <%= form.date_field :expiration_date %></p>

  <%= form.submit %>
<% end %>

app/views/promotions/search.html.erb
<p><%= link_to  'Voltar', promotions_path %></p>

<h1>Resultados da busca</h1>

<% unless @result_set.any? %>
  <p>Nenhum resultado encontrado!</p>
<% end %>

<% @result_set.each do |result| %>
  <p><%= result.class %>:</p>

  <% if result.is_a?(Promotion) %>
    <p><%= result.name %></p>
    <p><%= result.description %></p>
  <% else %>
    <p><%= result.code %></p>
  <% end %>
<% end %>

app/views/promotions/show.html.erb
<p><%= link_to  'Voltar', promotions_path %></p>

<h3>Promoção: <%= @promotion.name %></h3>
<p>Criada por: <%= @promotion.admin.email %></p>
<p>Descrição: <%= @promotion.description %></p>
<p>Código: <%= @promotion.code %></p>
<p>Desconto: <%= number_to_percentage @promotion.discount_rate, precision: 2, separator: ',' %></p>
<p>Data de expiração: <%= @promotion.expiration_date.strftime('%d/%m/%Y') %></p>
<p>Quantidade de cupons: <%= @promotion.coupon_quantity %></p>

<p>
  <% if @promotion.categories.any? %>
    Categorias:
    <% @promotion.categories.each do |category| %>
      #<%= category.name %>
    <% end %>
  <% end %>
</p>

<p>
  <%= link_to 'Editar promoção', edit_promotion_path(@promotion) %> | 
  <%= link_to 'Apagar promoção', @promotion, method: :delete %>
</p>

<p>
  <% if @promotion.approved? %>
    <p><%= t :status %><p>
  <% end %>
</p>

<p>
  <% unless current_admin == @promotion.admin %>
    <%= link_to 'Aprovar promoção', approve_promotion_path, method: :post %>
  <% end %>
</p>

<p>
  <% unless @promotion.coupons.any? %>
    <%= link_to 'Gerar cupons', creates_coupons_promotion_path, method: :post %>
  <% end %>
</p>
<hr>

<% if flash[:notice].present? %>
  <p><%= flash[:notice] %></p>
<% end %>

<h3>Cupons</h3>
<% @promotion.coupons.each do |coupon| %>
  <div id="coupon-<%= coupon.id %>">
    <%= coupon.code %>(<%= t(coupon.status) %>)
    <% if coupon.active? %>
      <%= link_to 'Inativar', inactivate_coupon_path(coupon), method: :post %>
    <% else %>
      <%= link_to 'Ativar', activate_coupon_path(coupon), method: :post %>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<h1>Promotion System</h1>
<p>
  <% if admin_signed_in? %>
    <%= current_admin.email %> | 
    <%= link_to "Logout", destroy_admin_session_path, method: :delete %>
  <% else %>
    <%= link_to "Login", new_admin_session_path %>
  <% end %>
</p>
<hr>